// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GestorDeTareas.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260511103111_QuitarClavePrimariaCompuesta")]
    partial class QuitarClavePrimariaCompuesta
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GestorDeTareas.Models.Amigos", b =>
                {
                    b.Property<int>("IdAmigos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAmigos"));

                    b.Property<DateTime>("FechaInicioAmistad")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario2")
                        .HasColumnType("integer");

                    b.Property<int>("TiposEstado")
                        .HasColumnType("integer");

                    b.HasKey("IdAmigos");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("IdUsuario2");

                    b.ToTable("Amigos");
                });

            modelBuilder.Entity("GestorDeTareas.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("ContrasenaUsuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CorreoUsuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("EstaEliminado")
                        .HasColumnType("boolean");

                    b.Property<string>("FriendTag")
                        .HasColumnType("text");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Tarea", b =>
                {
                    b.Property<int>("IdTarea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTarea"));

                    b.Property<string>("DescripcionTarea")
                        .HasColumnType("text");

                    b.Property<bool?>("EstaEliminado")
                        .HasColumnType("boolean");

                    b.Property<int?>("EstadosTarea")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaCreacionTarea")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdUsuarioDeLaTarea")
                        .HasColumnType("integer");

                    b.Property<string>("NombreTarea")
                        .HasColumnType("text");

                    b.Property<int>("TiposTarea")
                        .HasColumnType("integer");

                    b.HasKey("IdTarea");

                    b.ToTable("Tareas");

                    b.HasDiscriminator<int>("TiposTarea").HasValue(0);

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("GestorDeTareas.Models.TareaUrgente", b =>
                {
                    b.HasBaseType("Tarea");

                    b.Property<DateTime?>("FechaLimite")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("TienePrioridad")
                        .HasColumnType("boolean");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("GestorDeTareas.Models.Amigos", b =>
                {
                    b.HasOne("GestorDeTareas.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestorDeTareas.Models.Usuario", "Usuario2")
                        .WithMany()
                        .HasForeignKey("IdUsuario2")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");

                    b.Navigation("Usuario2");
                });
#pragma warning restore 612, 618
        }
    }
}
