// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestorDeTareas.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260430080503_MigracionInicial")]
    partial class MigracionInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestorDeTareas.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("ContrasenaUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("EstaEliminado")
                        .HasColumnType("bit");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Tarea", b =>
                {
                    b.Property<int>("IdTarea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTarea"));

                    b.Property<string>("DescripcionTarea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("EstaEliminado")
                        .HasColumnType("bit");

                    b.Property<int?>("EstadosTarea")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaCreacionTarea")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdUsuarioDeLaTarea")
                        .HasColumnType("int");

                    b.Property<string>("NombreTarea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TiposTarea")
                        .HasColumnType("int");

                    b.HasKey("IdTarea");

                    b.ToTable("Tareas");

                    b.HasDiscriminator<int>("TiposTarea").HasValue(1);

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("GestorDeTareas.Models.TareaUrgente", b =>
                {
                    b.HasBaseType("Tarea");

                    b.Property<DateTime?>("FechaLimite")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("TienePrioridad")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue(2);
                });
#pragma warning restore 612, 618
        }
    }
}
